import 'settings_service.dart';

class LanguageService {
  static const Map<String, Map<String, String>> _translations = {
    'en': {
      'app_name': 'Bill Buddy',
      'split_expenses': 'Split expenses in seconds',
      'your_name': 'Your Name',
      'enter_name': 'Enter your name',
      'group_code': 'Group Code (Optional)',
      'enter_code': 'Enter code to join',
      'create_group': 'Create New Group',
      'join_group': 'Join Existing Group',
      'no_login': 'No login required • Real-time sync • Privacy first',
      'add_expense': 'Add Expense',
      'amount': 'Amount',
      'description': 'Description',
      'what_for': 'What was this for?',
      'who_paid': 'Who paid?',
      'you': 'You',
      'balance_summary': 'Balance Summary',
      'no_expenses': 'No expenses yet',
      'add_first': 'Tap + to add your first expense',
      'delete_expense': 'Delete Expense',
      'confirm_delete': 'Are you sure you want to delete this expense?',
      'cancel': 'Cancel',
      'delete': 'Delete',
      'paid_by': 'Paid by',
      'owes': 'owes',
      'to': 'to',
      'settled': 'All settled!',
      'calculation_details': 'Calculation Details',
      'total_expenses': 'Total Expenses',
      'per_person': 'Per Person',
      'individual_share': 'Individual Share',
      'balance_explanation': 'Balance Explanation',
      'language': 'Language',
      'calculations': 'Calculations',
      'settings': 'Settings',
      'total_spent': 'Total Amount Spent',
      'select_language': 'Select Language',
      'enter_name_error': 'Please enter your name',
      'group_not_found': 'Group not found. Please check the code.',
      'error_occurred': 'An error occurred',
    },
    'hi': {
      'app_name': 'बिल बडी',
      'split_expenses': 'सेकंडों में खर्च बांटें',
      'your_name': 'आपका नाम',
      'enter_name': 'अपना नाम दर्ज करें',
      'group_code': 'ग्रुप कोड (वैकल्पिक)',
      'enter_code': 'जुड़ने के लिए कोड दर्ज करें',
      'create_group': 'नया ग्रुप बनाएं',
      'join_group': 'मौजूदा ग्रुप में शामिल हों',
      'no_login': 'लॉगिन आवश्यक नहीं • रियल-टाइम सिंक • गोपनीयता पहले',
      'add_expense': 'खर्च जोड़ें',
      'amount': 'राशि',
      'description': 'विवरण',
      'what_for': 'यह किस लिए था?',
      'who_paid': 'किसने भुगतान किया?',
      'you': 'आप',
      'balance_summary': 'बैलेंस सारांश',
      'no_expenses': 'अभी तक कोई खर्च नहीं',
      'add_first': 'पहला खर्च जोड़ने के लिए + दबाएं',
      'delete_expense': 'खर्च हटाएं',
      'confirm_delete': 'क्या आप वाकई इस खर्च को हटाना चाहते हैं?',
      'cancel': 'रद्द करें',
      'delete': 'हटाएं',
      'paid_by': 'द्वारा भुगतान',
      'owes': 'देना है',
      'to': 'को',
      'settled': 'सब ठीक है!',
      'calculation_details': 'गणना का विवरण',
      'total_expenses': 'कुल खर्च',
      'per_person': 'प्रति व्यक्ति',
      'individual_share': 'व्यक्तिगत हिस्सा',
      'balance_explanation': 'बैलेंस की व्याख्या',
      'language': 'भाषा',
      'calculations': 'गणना',
      'settings': 'सेटिंग्स',
      'total_spent': 'कुल खर्च की गई राशि',
      'select_language': 'भाषा चुनें',
    },
    'te': {
      'app_name': 'బిల్ బడ్డీ',
      'split_expenses': 'సెకన్లలో ఖర్చులను పంచుకోండి',
      'your_name': 'మీ పేరు',
      'enter_name': 'మీ పేరు నమోదు చేయండి',
      'group_code': 'గ్రూప్ కోడ్ (ఐచ్ఛికం)',
      'enter_code': 'చేరడానికి కోడ్ నమోదు చేయండి',
      'create_group': 'కొత్త గ్రూప్ సృష్టించండి',
      'join_group': 'ఉన్న గ్రూప్‌లో చేరండి',
      'no_login': 'లాగిన్ అవసరం లేదు • రియల్-టైమ్ సింక్ • గోప్యత మొదట',
      'add_expense': 'ఖర్చు జోడించండి',
      'amount': 'మొత్తం',
      'description': 'వివరణ',
      'what_for': 'ఇది దేని కోసం?',
      'who_paid': 'ఎవరు చెల్లించారు?',
      'you': 'మీరు',
      'balance_summary': 'బ్యాలెన్స్ సారాంశం',
      'no_expenses': 'ఇంకా ఖర్చులు లేవు',
      'add_first': 'మొదటి ఖర్చును జోడించడానికి + నొక్కండి',
      'delete_expense': 'ఖర్చు తొలగించండి',
      'confirm_delete': 'మీరు నిజంగా ఈ ఖర్చును తొలగించాలనుకుంటున్నారా?',
      'cancel': 'రద్దు చేయండి',
      'delete': 'తొలగించండి',
      'paid_by': 'చెల్లించినది',
      'owes': 'రుణం',
      'to': 'కు',
      'settled': 'అంతా సరిపెట్టుకున్నారు!',
      'calculation_details': 'గణన వివరాలు',
      'total_expenses': 'మొత్తం ఖర్చులు',
      'per_person': 'ప్రతి వ్యక్తికి',
      'individual_share': 'వ్యక్తిగత వాటా',
      'balance_explanation': 'బ్యాలెన్స్ వివరణ',
      'language': 'భాష',
      'calculations': 'గణనలు',
    },
    'ta': {
      'app_name': 'பில் பட்டி',
      'split_expenses': 'விநாடிகளில் செலவுகளைப் பிரிக்கவும்',
      'your_name': 'உங்கள் பெயர்',
      'enter_name': 'உங்கள் பெயரை உள்ளிடவும்',
      'group_code': 'குழு குறியீடு (விருப்பம்)',
      'enter_code': 'சேர குறியீட்டை உள்ளிடவும்',
      'create_group': 'புதிய குழுவை உருவாக்கவும்',
      'join_group': 'உள்ள குழுவில் சேரவும்',
      'no_login': 'உள்நுழைவு தேவையில்லை • நேரடி ஒத்திசைவு • தனியுரிமை முதலில்',
      'add_expense': 'செலவு சேர்க்கவும்',
      'amount': 'தொகை',
      'description': 'விளக்கம்',
      'what_for': 'இது எதற்காக?',
      'who_paid': 'யார் செலுத்தினார்?',
      'you': 'நீங்கள்',
      'balance_summary': 'இருப்பு சுருக்கம்',
      'no_expenses': 'இன்னும் செலவுகள் இல்லை',
      'add_first': 'முதல் செலவைச் சேர்க்க + ஐ அழுத்தவும்',
      'delete_expense': 'செலவை அழிக்கவும்',
      'confirm_delete': 'இந்த செலவை நிச்சயமாக அழிக்க விரும்புகிறீர்களா?',
      'cancel': 'ரத்து செய்',
      'delete': 'அழி',
      'paid_by': 'செலுத்தியவர்',
      'owes': 'கடன்',
      'to': 'க்கு',
      'settled': 'எல்லாம் தீர்ந்தது!',
      'calculation_details': 'கணக்கீட்டு விவரங்கள்',
      'total_expenses': 'மொத்த செலவுகள்',
      'per_person': 'ஒரு நபருக்கு',
      'individual_share': 'தனிப்பட்ட பங்கு',
      'balance_explanation': 'இருப்பு விளக்கம்',
      'language': 'மொழி',
      'calculations': 'கணக்கீடுகள்',
    },
    'kn': {
      'app_name': 'ಬಿಲ್ ಬಡ್ಡಿ',
      'split_expenses': 'ಸೆಕೆಂಡುಗಳಲ್ಲಿ ವೆಚ್ಚಗಳನ್ನು ಹಂಚಿಕೊಳ್ಳಿ',
      'your_name': 'ನಿಮ್ಮ ಹೆಸರು',
      'enter_name': 'ನಿಮ್ಮ ಹೆಸರನ್ನು ನಮೂದಿಸಿ',
      'group_code': 'ಗುಂಪು ಕೋಡ್ (ಐಚ್ಛಿಕ)',
      'enter_code': 'ಸೇರಲು ಕೋಡ್ ನಮೂದಿಸಿ',
      'create_group': 'ಹೊಸ ಗುಂಪನ್ನು ರಚಿಸಿ',
      'join_group': 'ಅಸ್ತಿತ್ವದಲ್ಲಿರುವ ಗುಂಪಿಗೆ ಸೇರಿ',
      'no_login': 'ಲಾಗಿನ್ ಅಗತ್ಯವಿಲ್ಲ • ನೈಜ-ಸಮಯ ಸಿಂಕ್ • ಗೌಪ್ಯತೆ ಮೊದಲು',
      'add_expense': 'ವೆಚ್ಚ ಸೇರಿಸಿ',
      'amount': 'ಮೊತ್ತ',
      'description': 'ವಿವರಣೆ',
      'what_for': 'ಇದು ಯಾವುದಕ್ಕಾಗಿ?',
      'who_paid': 'ಯಾರು ಪಾವತಿಸಿದರು?',
      'you': 'ನೀವು',
      'language': 'ಭಾಷೆ',
      'calculations': 'ಲೆಕ್ಕಾಚಾರಗಳು',
      'settings': 'ಸೆಟ್ಟಿಂಗ್‌ಗಳು',
      'total_spent': 'ಒಟ್ಟು ಖರ್ಚು ಮಾಡಿದ ಮೊತ್ತ',
      'select_language': 'ಭಾಷೆ ಆಯ್ಕೆ ಮಾಡಿ',
      'enter_name_error': 'ದಯವಿಟ್ಟು ನಿಮ್ಮ ಹೆಸರನ್ನು ನಮೂದಿಸಿ',
      'group_not_found': 'ಗುಂಪು ಸಿಗಲಿಲ್ಲ. ದಯವಿಟ್ಟು ಕೋಡ್ ಪರಿಶೀಲಿಸಿ.',
      'error_occurred': 'ಒಂದು ದೋಷ ಸಂಭವಿಸಿದೆ',
    },
    'ml': {
      'app_name': 'ബിൽ ബഡ്ഡി',
      'your_name': 'നിങ്ങളുടെ പേര്',
      'language': 'ഭാഷ',
      'calculations': 'കണക്കുകൾ',
    },
    'gu': {
      'app_name': 'બિલ બડી',
      'your_name': 'તમારું નામ',
      'language': 'ભાષા',
      'calculations': 'ગણતરીઓ',
    },
    'mr': {
      'app_name': 'बिल बडी',
      'your_name': 'तुमचे नाव',
      'language': 'भाषा',
      'calculations': 'गणना',
    },
    'bn': {
      'app_name': 'বিল বাডি',
      'your_name': 'আপনার নাম',
      'language': 'ভাষা',
      'calculations': 'গণনা',
    },
    'or': {
      'app_name': 'ବିଲ୍ ବଡ଼ି',
      'your_name': 'ଆପଣଙ୍କ ନାମ',
      'language': 'ଭାଷା',
      'calculations': 'ଗଣନା',
    },
    'pa': {
      'app_name': 'ਬਿੱਲ ਬੱਡੀ',
      'your_name': 'ਤੁਹਾਡਾ ਨਾਮ',
      'language': 'ਭਾਸ਼ਾ',
      'calculations': 'ਗਿਣਤੀਆਂ',
    },
  };

  static const List<Map<String, String>> supportedLanguages = [
    {'code': 'en', 'name': 'English', 'nativeName': 'English'},
    {'code': 'hi', 'name': 'Hindi', 'nativeName': 'हिंदी'},
    {'code': 'te', 'name': 'Telugu', 'nativeName': 'తెలుగు'},
    {'code': 'ta', 'name': 'Tamil', 'nativeName': 'தமிழ்'},
    {'code': 'kn', 'name': 'Kannada', 'nativeName': 'ಕನ್ನಡ'},
    {'code': 'ml', 'name': 'Malayalam', 'nativeName': 'മലയാളം'},
    {'code': 'gu', 'name': 'Gujarati', 'nativeName': 'ગુજરાતી'},
    {'code': 'mr', 'name': 'Marathi', 'nativeName': 'मराठी'},
    {'code': 'bn', 'name': 'Bengali', 'nativeName': 'বাংলা'},
    {'code': 'or', 'name': 'Odia', 'nativeName': 'ଓଡ଼ିଆ'},
    {'code': 'pa', 'name': 'Punjabi', 'nativeName': 'ਪੰਜਾਬੀ'},
  ];

  static String get currentLanguage => SettingsService().currentLanguage;

  static void setLanguage(String languageCode) {
    if (_translations.containsKey(languageCode)) {
      SettingsService().setLanguage(languageCode);
    }
  }

  static String translate(String key) {
    String currentLang = SettingsService().currentLanguage;
    return _translations[currentLang]?[key] ?? 
           _translations['en']?[key] ?? 
           key;
  }

  static String t(String key) => translate(key);
}